server:
  port: 8061
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.174.128:3306/test?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.174.128
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#security:
    #  oauth2:
      #   client:
      #     client-id: leige
    #   client-secret: 123456
leige:
  security:
    oauth2:
      clients[0]:
        clientId: S001
        clientSecret: 123456
        accessTokenValiditySeconds: 3000
        authorizedGrantTypes[0]: refresh_token
        authorizedGrantTypes[1]: password
        scopes[0]: all
      clients[1]:
        clientId: S002
        clientSecret: 201314
        accessTokenValiditySeconds: 3000
