server:
  port: 8060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.174.128:3306/test?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.174.128
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: none
leige:
  security:
    browser:
      loginPage: /leige-signIn.html
      loginType: REDIRECT
