server:
  port: 8060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/leige_security?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: leige
    password: 201314
  redis:
    database: 0
    host: localhost
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: none
leige:
  security:
    browser:
      loginPage: /leige-signIn.html
      loginType: REDIRECT
